version: 0.2
env:
  variables:
     RANCHER_CLI_VERSION: "v0.6.2"
phases:
  pre_build:
    commands:
      #- curl -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
      - echo Logging in to Amazon ECR...
      #- $(docker run -e AWS_REGION -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_ACCOUNT_ID behance/ecr-login  | sed -e 's/-e none//g')
      - docker login --username=$DOCKER_LOGIN --password=$DOCKER_PASSWORD --email=$DOCKER_EMAIL
  build:
    commands:
      - echo Build started on `date`
      - echo Building the code image...
      - docker build -t $DOCKER_LOGIN/$IMAGE_REPO_NAME:$IMAGE_TAG .
      #- docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image..
      - docker push $DOCKER_LOGIN/$IMAGE_REPO_NAME:$IMAGE_TAG
